### ISSUE TITLE
Potential false negative (failed test) lib version checks on minified files

### ISSUE THREAD

**Issue by m-gagne** [deltakosh/DXCrawler#13]
# Description
When checking a minified version of bootstrap.js the crawler it is detecting a jQuery version of 3.3.4 against the site http://www.gotsomething.com (the current major version of jQuery is 2, so right away you should see a problem here.)

Although the libs test pass, it's improperly reporting bootstrap.js as jQuery because of the header regex check at  `lib\checks\check-libs.js:305`

# Issue
The jQuery test inappropriately identifies bootstrap.js as jQuery and incorrectly uses the version found in the header comment (3.3.4)

The regular expression can be found at `line 305` in `lib\checks\check-libs.js`

        //If header fails, we look with another pattern
        var regex = /(?:jquery[,\)].*=")(\d+\.\d+)(\..*?)"/gi;
        
The issue is the `.*="` part of the match, because what is happening is if the source code contains `jquery,` or `jquery(` then ANYTHING inbetween and finally a `=0.0` (where 0 is any digit) it will match. You can see how this results identifying jQuery (with an incorrect version) here: https://regex101.com/r/nQ6rA3/1

# Further Details
Site being scanned: http://www.gotsomething.com
JavaScript Source Url: http://gotsomething.com/wp-content/themes/materialwp-materialwp/bower_components/bootstrap/dist/js/bootstrap.min.js?ver=3.3.4

# Recommended fix
Limit the range with a quantifier other than `.*` in all regular expressions

So instead of `var regex = /(?:jquery[,\)].*=")(\d+\.\d+)(\..*?)"/gi;` do `var regex = /(?:jquery[,\)].{0,200}=")(\d+\.\d+)(\..*?)"/gi; this way the match has to happen within 200 characters of the first match on jQuery

**Comment by deltakosh** [comment]
Sounds like a good improvement. can you provide a PR?
