### ISSUE TITLE
Analytics Tracking Code causes failure due to Browser Detection 

### ISSUE THREAD

**Issue by m-gagne** [deltakosh/DXCrawler#14]
Various analytics/tracking scripts will often pass browser information back to the collection service. One example is the Adobe Visitor Tracking API (Omniture) which uses `navigator.userAgent` to record browser information.

Should there be a whitelist of scripts that are ignored if their use of browser detection code does not affect the markup or features of the site?

Example offending code:

	var t = e({
		OmniWeb: /OmniWeb/,
		"Opera Mini": /Opera Mini/,
		"Opera Mobile": /Opera Mobi/,
		Opera: /Opera/,
		"Mobile Safari": /Mobile(\/[0-9A-z]+)? Safari/,
		Chrome: /Chrome/,
		Firefox: /Firefox/,
		"IE Mobile": /IEMobile/,
		IE: /MSIE|Trident/,
		Safari: /Safari/
	}),
		n = e({
			iOS: /iPhone|iPad|iPod/,
			Blackberry: /BlackBerry/,
			"Symbian OS": /SymbOS/,
			Maemo: /Maemo/,
			Android: /Android [0-9\.]+;/,
			Linux: / Linux /,
			Unix: /FreeBSD|OpenBSD|CrOS/,
			Windows: /[\( ]Windows /,
			MacOS: /Macintosh;/
		}),
		a = e({
			iPhone: /iPhone/,
			iPad: /iPad/,
			iPod: /iPod/,
			Nokia: /SymbOS|Maemo/,
			"Windows Phone": /IEMobile/,
			Blackberry: /BlackBerry/,
			Android: /Android [0-9\.]+;/,
			Desktop: /.*/
		}),
		i = navigator.userAgent;
	k.browserInfo = {
		browser: t(i),
		os: n(i),
		deviceType: a(i)
	}

**Comment by deltakosh** [comment]
Related to #18
