### ISSUE TITLE
Latest version of Modernizer not included in check-libs.js

### ISSUE THREAD

**Issue by m-gagne** [deltakosh/DXCrawler#19]
Modernizer 2.8.3 is not included in the `minVersions` definition for Modernizr

        name: "Modernizr",
        minVersions: [
            { major: "1.1.", minor: "" },
            { major: "2.5.", minor: "2" },
            { major: "2.6.", minor: "2" },
            { major: "2.7.", minor: "1" }
        ]

**Comment by deltakosh** [comment]
Correct. Can you submit a PR?

**Comment by deltakosh** [comment]
up:)

**Comment by m-gagne** [comment]
PR submitted :)

**Comment by m-gagne** [comment]
Closing as it was fixed with PR #22
