### ISSUE TITLE
Is revision version checking really necessary for JS Lib tests?

### ISSUE THREAD

**Issue by m-gagne** [deltakosh/DXCrawler#23]
Example a site using jQuery version `1.10.1` will fail because it does not match the minimum revision for that particular minor release which is `1.10.2`.

If we look at the [change list for 1.10.2](http://blog.jquery.com/2013/07/03/jquery-1-10-2-and-2-0-3-released/) there are 
* zero fixes/changes related to Edge
* a fix related to node-testswarm
* a fix related to IE7 & IE 10
* a CSS selector issue for -webkit prefix

For the purposes of Edge, would a more simplistic check of most recent Edge compatible major.minor suffice?

**Comment by deltakosh** [comment]
Hello my question is then: why do you want to simplify this process? Why not just updating the config file to define that minimal jQuery version is 1.10.1?

**Comment by m-gagne** [comment]
Good point, that's a much easier change :) If approved I can get a PR ready (after fixing the tests which will fail)

**Comment by deltakosh** [comment]
go :)

**Comment by m-gagne** [comment]
So after looking at the code some more if we did simply change the revision version to 0 say like so for jQuery 

            { major: "1.6.", minor: "0" },
            { major: "1.7.", minor: "0" },
            { major: "1.8.", minor: "0" },
            { major: "1.9.", minor: "0" },
            { major: "1.10.", minor: "0" },
            { major: "1.11.", minor: "0" },
            { major: "2.0.", minor: "0" },
            { major: "2.1.", minor: "0" }

Then aren't we just saying if version >= "1.6" ? in which case we can really simplify the code and unit tests.

So we can keep revision checks in the version checking code should we ever need that ability but simply change the `minVersions` for jQuery to:

        name: "jQuery",
        minVersions: [
            { major: "1.6.", minor: "0" },
        ],

Which would mean as long as the version found on the site is >= 1.6 they pass. This would have a pretty large impact so we should evaluate carefully.

**Comment by deltakosh** [comment]
adding @csuwildcat for validation

**Comment by csuwildcat** [comment]
I did not find any cases where intermediate library versions failed operational testing, so you probably can erase all versions besides the lowest minimum version. (I left the intermediate versions in because I wasn't 100% sure if they were used for anything else)

**Comment by m-gagne** [comment]
The way the code works is it iterates each defined `minVersion` and verifies that the detected version is greater than the revision of the matching major.minor version

Example using the following `minVersions`

        minVersions: [
            { major: "1.6.", minor: "0" },
            { major: "1.7.", minor: "2" },
            { major: "1.8.", minor: "2" },
            { major: "1.9.", minor: "1" },
            { major: "1.10.", minor: "2" },
            { major: "1.11.", minor: "1" },
            { major: "2.0.", minor: "3" },
            { major: "2.1.", minor: "1" }
        ],


a detected jQuery version of 1.7.1 would **fail**, but 1.6.0 would **pass**.

**Comment by csuwildcat** [comment]
@m-gagne If that's the case, I'd definitely delete all but the lowest version.

**Comment by m-gagne** [comment]
So the ideal logic flow then is

1. Have a single defined `minVersion`, perhaps even remove the array entirely
2. Update validation logic to check if detected version is greater than or equal to the min version
3. Still validate [major].[minor].[revision] but reset defined libs to `.0` for revision unless there is a specific revision that fixes something for Edge

**Comment by m-gagne** [comment]
bump :) /cc @csuwildcat & @deltakosh

**Comment by csuwildcat** [comment]
Sounds like the right course of action to me. Do you have a patch?

**Comment by m-gagne** [comment]
I'll get ready today, code change is easy, but there are a lot of unit tests that need to be removed/reworked that check for specific revisions etc.
